name = "power"
name_pretty = "Power"
icon = "system-shutdown"

# ["󰤄     Suspend"]="lio-launch-floating-terminal --silent 'gum confirm --timeout=10s --affirmative Suspend --negative Cancel Suspend? && systemctl suspend'"
# ["     Logout"]="lio-launch-floating-terminal --silent 'gum confirm --timeout=10s --affirmative Logout --negative Cancel Logout? && uwsm stop'"
# ["󰜉     Reboot"]="lio-launch-floating-terminal --silent 'gum confirm --timeout=10 --affirmative Reboot --negative Cancel Reboot? && systemctl reboot'"
# ["󰐥     Shutdown"]="lio-launch-floating-terminal --silent 'gum confirm --timeout=10s --affirmative Shutdown --negative Cancel Shutdown? && systemctl poweroff'"

[[entries]]
text = "Shutdown"
actions = { "shutdown" = "lio-launch-floating-terminal --silent 'gum confirm --timeout=10s --affirmative Shutdown --negative Cancel Shutdown? && systemctl poweroff'" }
icon = "system-shutdown"

[[entries]]
text = "Reboot"
actions = { "reboot" = "lio-launch-floating-terminal --silent 'gum confirm --timeout=10 --affirmative Reboot --negative Cancel Reboot? && systemctl reboot'" }
icon = "system-reboot"

[[entries]]
text = "Suspend"
actions = { "suspend" = "lio-launch-floating-terminal --silent 'gum confirm --timeout=10s --affirmative Suspend --negative Cancel Suspend? && systemctl suspend'" }
icon = "system-suspend"

[[entries]]
text = "Logout"
actions = { "logout" = "lio-launch-floating-terminal --silent 'gum confirm --timeout=10s --affirmative Logout --negative Cancel Logout? && uwsm stop'" }
icon = "system-log-out"

[[entries]]
text = "Lock Screen"
actions = { "lock" = "playerctl --all-players pause & hyprlock" }
icon = "system-lock-screen"
