name = "screenshot"
name_pretty = "Screenshot"
icon = "camera"

[[entries]]
text = "Selection"
actions = { "selection" = "lio-cmd-screenshot" }
icon = "selection"

[[entries]]
text = "Window"
actions = { "window" = "lio-cmd-screenshot window" }
icon = "window"

[[entries]]
text = "Display"
actions = { "display" = "lio-cmd-screenshot output" }
icon = "camera"
