name = "settings"
name_pretty = "Settings"
icon = "settings"
# global_search = false

        # ["     Toggle Nightlight"]="lio-toggle-nightlight"
        # ["󰓦     Sync Dotfiles"]="lio-launch-floating-terminal chezmoi apply"
        # ["     Screenshot"]="show_screenshot_menu"
        # ["     Audio"]="lio-launch-floating-terminal --silent 'wiremix'"
        # ["     YubiKey 2fa"]="show_yubikey_codes"
        # ["     Clipboard"]="lio-launch-floating-terminal --silent clipse"
        # ["     SSH"]="show_ssh_menu"
        # ["     Idle Inhibit"]="lio-idleinhibit"
        # ["     Bluetooth"]="lio-launch-floating-terminal --silent 'bluetui'"
        # ["     WIFI"]="lio-launch-floating-terminal --silent 'impala'"


[[entries]]
text = "Toggle Nightlight"
actions = { "toggle" = "lio-toggle-nightlight" }
icon = "night-light-symbolic"

[[entries]]
text = "Sync Dotfiles"
actions = { "sync" = "lio-launch-floating-terminal chezmoi apply" }
icon = "folder-sync"

[[entries]]
text = "Audio"
actions = { "launch" = "lio-launch-floating-terminal --silent wiremix" }
icon = "audio-volume-high"

[[entries]]
text = "WIFI"
actions = { "launch" = "lio-launch-floating-terminal --silent impala" }
icon = "network-wireless"

[[entries]]
text = "Bluetooth"
actions = { "launch" = "lio-launch-floating-terminal --silent bluetui" }
icon = "bluetooth"

[[entries]]
text = "YubiKey 2FA"
actions = { "launch" = "lio-cmd-yubikey" }
icon = "gtk-authentication"
