name = "settings"
name_pretty = "Settings"
icon = "settings"

[[entries]]
text = "Toggle Nightlight"
actions = { "toggle" = "lio-toggle-nightlight" }
icon = "night-light-symbolic"

[[entries]]
text = "Sync Dotfiles"
actions = { "sync" = "lio-launch-floating-terminal chezmoi apply" }
icon = "folder-sync"

[[entries]]
text = "Audio/Volume"
actions = { "launch" = "lio-launch-floating-terminal --silent wiremix" }
icon = "audio-volume-high"

[[entries]]
text = "WIFI"
actions = { "launch" = "lio-launch-floating-terminal --silent impala" }
icon = "network-wireless"

[[entries]]
text = "Bluetooth"
actions = { "launch" = "lio-launch-floating-terminal --silent bluetui" }
icon = "bluetooth"

[[entries]]
text = "YubiKey 2FA"
actions = { "launch" = "lio-cmd-yubikey" }
icon = "gtk-authentication"

[[entries]]
text = "Color Picker"
actions = { "launch" = "hyprpicker --autocopy" }
icon = "color-picker"
